# Generated by Django 5.1.2 on 2025-02-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
